version: '3'

networks:
  student:

services:
  site:
    image: nginx:stable-alpine
    container_name: student_site
    hostname: 'student'
    ports:
      - 8100:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/custom_nginx_proxy.conf:/etc/nginx/conf.d/custom_nginx_proxy.conf
    depends_on:
      - php
    networks:
      - student

  php:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    container_name: student_php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php_custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - 9000
    networks:
      - student

  composer:
    image: composer:2
    container_name: student_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - student

  artisan:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    container_name: student_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - student

  db:
    image: mariadb
    restart: unless-stopped
    container_name: student_database
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: student_staging
      MYSQL_USER: root
      MYSQL_PASSWORD: student383!
      MYSQL_ROOT_PASSWORD: student383!
    networks:
      - student
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: student_phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: student383!
    depends_on:
      - db
    networks:
      - student